### PR TITLE
Remove yjit_backend to help with upstreaming

### PR DESCRIPTION
**Pull request by XrXr**
The new backend isn't used at the moment and adds to our diff against
upstream so remove it for now. We can reverse the removal later with git
history.

### CODE REVIEW

**Comment by noahgibbs** [comment]
The backend commits shouldn't be in the rebased branch - I left them out on purpose.

**Comment by XrXr** [comment]
Right, but the build is breaking on the rebase branch because the removal is incomplete.

**Comment by maximecb** [comment]
Sure thing. @XrXr can you make sure to leave these on a branch or have a tag for them?

**Comment by XrXr** [comment]
Okay, I made a snapshot of main at https://github.com/Shopify/yjit/tree/new-backend.

**Pull request merged**
